# Configuración de estrategia
strategy:
  time_frame: M5
  leverage: 5

# Umbrales de trading
thresholds:
  order_book_imbalance: 0.5
  delta_volume: 200 # BTC
  sentiment_score:
    positive: 0.7
    negative: 0.3

# Gestión de riesgo
risk_management:
  per_trade: 1%
  daily: 5%
  max_leverage: 5x

# Configuración de exchanges
exchanges:
  binance:
    pair: BTC/USDT
    futures: true
    perpetual: true
